USE [master]
GO

/****** Object:  Database [Earth]    Script Date: 7.2.2017 ã. 20:12:35 ÷. ******/
CREATE DATABASE [Earth]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Earth', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\Earth.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Earth_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\Earth_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Earth] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Earth].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Earth] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Earth] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Earth] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Earth] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Earth] SET ARITHABORT OFF 
GO

ALTER DATABASE [Earth] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Earth] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Earth] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Earth] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Earth] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Earth] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Earth] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Earth] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Earth] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Earth] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Earth] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Earth] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Earth] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Earth] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Earth] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Earth] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Earth] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Earth] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Earth] SET  MULTI_USER 
GO

ALTER DATABASE [Earth] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Earth] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Earth] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Earth] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Earth] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Earth] SET QUERY_STORE = OFF
GO

USE [Earth]
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [Earth] SET  READ_WRITE 
GO


