//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Countries
{
    using System;
    using System.Collections.Generic;
    
    public partial class Countries
    {
        public Countries()
        {
            this.Cities = new HashSet<Cities>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int ContinentId { get; set; }
    
        public virtual ICollection<Cities> Cities { get; set; }
        public virtual Continents Continents { get; set; }
    }
}
